WebApp2.3/Models/ErrorViewModel.cs
namespace WebApp2._3.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApp2.3/Models/QuizViewModel.cs
namespace WebApp2._3.Models
{
    public class QuizViewModel
    {
        string[] operations = { "+", "-", "*" };

        private int X;
        private int Y;
        private string operation;
        private int rightAnswer { get; set; }
        public string question;
        public List<string> Results { get; set; } = new List<string>();

        public int answersCount = 0;
        public int rightAnswersCount = 0;


        public void SetRandomValues()
        {
            Random rand = new Random();
            X = rand.Next(0, 15);
            Y = rand.Next(0, 15);
            operation = operations[rand.Next(0, 3)];
            switch (operation)
            {
                case "+":
                    rightAnswer = X + Y; break;
                case "-":
                    rightAnswer = X - Y; break;
                case "*":
                    rightAnswer = X * Y; break;
            };
            question = $"{X} {operation} {Y} = ";
        }

        public void UppdateResults(int answer)
        {
            answersCount++;
            if (answer == rightAnswer)
            {
                rightAnswersCount++;
            }
            Results.Add($"{question} {answer}");
        }
    }
}

WebApp2.3/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApp2._3.Models;

namespace WebApp2._3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApp2.3/Controllers/MockupsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApp2._3.Models;

namespace WebApp2._3.Controllers
{
    public class MockupsController : Controller
    {
        private readonly ILogger<MockupsController> _logger;

        public MockupsController(ILogger<MockupsController> logger)
        {
            _logger = logger;
        }

        public IActionResult Mockups()
        {
            return View();
        }

        static readonly QuizViewModel quiz = new QuizViewModel();

        public IActionResult Quiz()
        {
            quiz.SetRandomValues();
            ViewBag.Question = quiz.question;
            return View();
        }

        [ActionName("Result")]
        public IActionResult QuizResult()
        {
            ViewBag.RightAnswersCount = quiz.rightAnswersCount;
            ViewBag.AnswersCount = quiz.answersCount;
            ViewBag.Results = quiz.Results;
            return View();
        }

        [HttpPost]
        [ActionName("Quiz")]
        public IActionResult QuizNext(int answer)
        {
            quiz.UppdateResults(answer);
            quiz.SetRandomValues();
            ViewBag.Question = quiz.question;
            return View("Quiz");
        }

        public IActionResult QuizFinish(int answer)
        {
            quiz.UppdateResults(answer);
            ViewBag.RightAnswersCount = quiz.rightAnswersCount;
            ViewBag.AnswersCount = quiz.answersCount;
            ViewBag.Results = quiz.Results;
            return View("Result");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApp2.3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApp2.3/Views/Mockups/Mockups.cshtml
@{
    ViewData["Title"] = "Quiz";
}

<div>
    <h1>Mockups</h1>
    <ul>
        <li><a asp-controller="Mockups" asp-action="Quiz">Quiz</a></li>
        <li><a asp-controller="Mockups" asp-action="Result">QuizResult</a></li>
    </ul>
</div>

WebApp2.3/Views/Mockups/Quiz.cshtml
@{
    ViewData["Title"] = "Quiz";
}

<div>
    <h1>Quiz</h1>
    <form method="post">
        <div>
            <p><b>@ViewBag.Question</b></p>
        </div>
        <div>
            <input name="answer" style="width:300px;" value="0" />
        </div>
        <br/>
        <div>
            <button name="next" type="submit" formaction="~/Mockups/Quiz">Next</button>
            <button name="finish" type="submit" formaction="~/Mockups/QuizFinish" class="blue">Finish</button>
        </div>
    </form>
</div>

WebApp2.3/Views/Mockups/Result.cshtml
@{
    ViewData["Title"] = "Quiz";
    int num = 1;
}

<div>
    <h1>Result</h1>
    <h3> Right answers @ViewBag.RightAnswersCount out of @ViewBag.AnswersCount</h3>

    @foreach (string result in ViewBag.Results)
    {
        <p>@(num++). @result</p>
    }
</div>

WebApp2.3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <h2>Backend2</h2>
        <nav><a asp-controller="Home" asp-action="Index">Home</a></nav>
        <nav><a asp-controller="Mockups" asp-action="Mockups">Mockups</a></nav>
    </header>

    <main>
        @RenderBody()
    </main>

    <footer>
            &copy; 2022 - Backend1
    </footer>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>